### ISSUE TITLE
How to use the code to do 3D face model registration on other database?

### ISSUE THREAD

**Issue by hyang428** [unibas-gravis/basel-face-pipeline#2]
could you add a little bit more comments about how to use the code on other 3D face model? e.g. a file that I can config  landmarks(yes/no), expressions(yes/no), 3D file format(ply, obj..). thx

**Comment by Andreas-Forster** [comment]
Thank you for your interest in using our pipepline. Your request is more a general support request related to also a lot of engineering work. This is out of scope of this project as we do not have the man power to support general feature requests. Thats why we close this issue here.

To continue, you can have a look at the tutorials and free online courses we provide (see http://gravis.dmi.unibas.ch/PMM/ → **"Lectures and Tutorials"**). They describe not only most of the theoretical concepts which are used in the pipeline, but also software details, e.g. how to load or save meshes and so on. 

When you still have problems, after working you through the lectures and tutorials, you can ask questions on the mailing list: https://groups.google.com/forum/#!categories/scalismo-faces/

Kind regards
