### ISSUE TITLE
How can i reconstruct 3dmm param from own image

### ISSUE THREAD

**Issue by KirtoXX** [unibas-gravis/basel-face-pipeline#7]
nice work!cool !
How can i reconstruct 3dmm param from own image?

**Comment by BernhardEgger** [comment]
Hi KirtoXX,

you just need the very last part of our pipeline refered to as "Face reconstruction from 2D images".
To run it, you need to put your image and a landmark file to the right directories (e.g. instead of the lfw images.

You can run this class here and put the files in the right directories:
https://github.com/unibas-gravis/basel-face-pipeline/blob/master/src/main/scala/fitting/experiments/QualitativeLFW.scala

to run execute:
sbt -mem 5000 "fitting.experiments.QualitativeLFW"

How to get the landmark file is described here:
https://github.com/unibas-gravis/basel-face-pipeline/issues/6

Best
Bernhard

**Comment by KirtoXX** [comment]
Hi,thanks for your answer.
I m a beginner of scala and your amazing project. Is it necessarty to register the BU-3DFE dataset first?casue I just wanna use bfm17 to reconstruct 3d model

**Comment by BernhardEgger** [comment]
Hi

you can skip step 0-5

Just make sure to download the basel face model to the right directory

data/modelbuilding/model/model2017-1_face12_nomouth.h5

The code will run the fitting for the basel face model first, and then for the other models (or crash if they dont exist)

Removing line 69 and 70 would avoid crashing in that case

To get more familiar with scala and our software you can also do this tutorial:
https://gravis.dmi.unibas.ch/PMM/lectures/fitting/
And replace the example image and landmarks there

**Comment by KirtoXX** [comment]
Hi, thanks for your answer!
 when I reading your tutorial,I find that there is no detal about expression，can you proivde some detal about  expression reconstruct

**Comment by BernhardEgger** [comment]
Hi,
the expression model is described in
Morphable Face Models - An Open Framework 
Thomas Gerig, Andreas Morel-Forster, Clemens Blumer, Bernhard Egger, Marcel Lüthi, Sandro Schönborn, Thomas Vetter
Conference on Automatic Face and Gesture Recognition, May 2018
DOI: https://doi.org/10.1109/FG.2018.00021
For fitting we just add them to the parameterset and treat them in the same way as shape and color components. There is nothing magic here. The mouth opening without explicit landmarks works because of the background model.
